services:
  motoserver:
    image: motoserver/moto:latest
    # image: motoserver/moto:5.0.17
    ports:
      - "3000:3000"
    environment:
      - MOTO_PORT=3000 # set moto listener port with env var